### ISSUE TITLE
Address line 2 text is showing over postcode

### ISSUE THREAD

**Issue by rudracomputech** [q-invoice/magento2-qinvoice-connect#1]
Invoice pdf is adding Address line 2 on over the postcode for both Billing and shipping address.

![image](https://user-images.githubusercontent.com/8698889/64110175-f88c9380-cd9e-11e9-8ab2-80a3c661caf9.png)

**Comment by casper824** [comment]
There is a newline in the <address> tag. The plugin will be updated shortly to support a 2nd address line. 

Edit: Support is added at the API. When a newline is detected, the first line is used as 'address', the second as 'address line 2'.
